## 创建数组

In [72]:
import numpy as np #导入库时候将名称改为别名np

In [73]:
arr1 = np.array([0.3, 0.5, 4.2])         # 创建一维数组
arr2 = np.array([[3, 4, 5], [4, 2, 1]])  # 创建二维数组
print(arr1)
print(arr2)
print(type(arr1)) #打印arr1数据类型type

[0.3 0.5 4.2]
[[3 4 5]
 [4 2 1]]
<class 'numpy.ndarray'>


In [74]:
# 查看数组的基础属性
print(arr1.shape) #查看数组的维数与元素个数，解构，##元组_结构
print(arr1.ndim) #维数
print(arr1.dtype) #数组类型
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(3,)
1
float64
(2, 3)
2
int32


In [75]:
# 初识数组的特点
list1 = [0.3, 0.5, 4.2]
arr1 = np.array([0.3, 0.5, 4.2])
print(list1)
print(arr1)

# 数组的向量化运算能力
# list1 ** 2     # 非法操作
print([i**2 for i in list1])
print(arr1 ** 2)

[0.3, 0.5, 4.2]
[0.3 0.5 4.2]
[0.09, 0.25, 17.64]
[ 0.09  0.25 17.64]


In [76]:
# 利用arange函数创建数组
arr3 = np.arange(0, 10)
arr4 = np.arange(10)
arr5 = np.arange(0, 1, 0.1)
print(arr3)
print(arr4)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [77]:
# 利用linspace函数创建数组
arr6 = np.linspace(0, 1, 11)
print(arr6)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [78]:
# 利用zeros函数创建数组
arr7 = np.zeros([3, 4, 5])
print(arr7)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [79]:
# 数组的数据类型
arr8 = np.array([3, 4, 5], dtype=np.float32)   # 在创建数组时，声明其数据类型
print(arr8)
print(arr8.dtype)

arr8[0] = 1.2    
print(arr8)
print(np.int32(arr8))   # 转换数组的数据类型

[3. 4. 5.]
float32
[1.2 4.  5. ]
[1 4 5]


In [80]:
# 生成随机数
print(np.random.random(10))   # 无约束条件下的随机数
print(np.random.rand(3, 4))   # 生成指定shape的均匀分布随机数
print(np.random.randn(2, 2, 3))   # 生成指定shape的正态分布随机数

[0.17686211 0.32176748 0.06864791 0.98942119 0.30739362 0.13614624
 0.57679229 0.16888608 0.88818192 0.05132514]
[[0.71053881 0.08590074 0.79555594 0.65237204]
 [0.24350481 0.93167947 0.99069162 0.7629989 ]
 [0.90477129 0.24507582 0.24386439 0.67139608]]
[[[ 0.93978028 -1.39487646 -0.85943937]
  [ 0.1521953   0.48971632 -1.10566766]]

 [[-1.17592839  0.18073964  0.03917536]
  [-1.44809722 -0.89112617 -1.38945007]]]


In [81]:
# 数组的索引
arr1 = np.array([0.3, 0.78, 0.24, 5, 3.2])
print(arr1)

# 一维数组的单个元素的索引
print(arr1[0])   
print(arr1[-5])

# 一维数组的多个元素的索引（切片）
print(arr1[1:3])
print(arr1[-4:-2])

res1 = arr1[3]
res2 = arr1[3:4]
print(res1, res1.shape)
print(res2, res2.shape)


[0.3  0.78 0.24 5.   3.2 ]
0.3
0.3
[0.78 0.24]
[0.78 0.24]
5.0 ()
[5.] (1,)


In [82]:
# 逻辑型索引
arr2 = np.array([2.3, 1.8, 4.5])
print(arr2)
print(arr2[[False, False, True]])
index = arr2 > 2
print(index)
print(arr2[index])

[2.3 1.8 4.5]
[4.5]
[ True False  True]
[2.3 4.5]


In [83]:
# 多维数组的索引
arr3 = np.arange(1, 13).reshape([3, 4])
print(arr3)
print(arr3[2, 3])
print(arr3[2, 0:])
print(arr3[:, 0])
print(arr3[1:3, 1:3])

print(arr3[2:, :])   # 注意返回值的shape

print(arr3[arr3[:, 0] > 4, :])  # 二维数组的逻辑型索引

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 9 10 11 12]
[1 5 9]
[[ 6  7]
 [10 11]]
[[ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
# 修改数组中的元素
arr3 = np.arange(1, 13).reshape([3, 4])
print(arr3)
arr3[0, 0] = 15
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[15  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
# 求解距离矩阵
n = 100    # 样本个数
x = np.linspace(1, 100, n)    # 样本的横坐标
y = np.linspace(1, 100, n)    # 样本的纵坐标

dist = np.zeros([n, n])       # 初始距离矩阵

for i in range(n):
    for j in range(n):
        dist[i, j] = np.sqrt((x[i] - x[j])**2 + (y[i] - y[j])**2)   # 计算欧式距离

print(x)
print(y)
print(dist)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.

In [86]:
# 数组形态变化
arr4 = np.arange(1, 13)
print(arr4)
print(arr4.reshape([3, 4]))  # 改变数组的shape
print(arr4.reshape([4, 3]))

arr5 = arr4.reshape([3, 4])   # 生成二维数组
print(arr5)
print(arr5.ravel())   # 数组展平
arr5.flatten()

arr6 = arr4.reshape([3, 4])
print(arr6)
print(np.vstack([arr5, arr6]))    # 纵向组合
print(np.hstack((arr5, arr6)))    # 横向组合

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


## 掌握 NumPy 矩阵与通用函数

In [87]:
import numpy as np

In [88]:
matr1 = np.mat("1 2 3;4 5 6;7 8 9")
print(matr1)
print(type(matr1))

matr2 = np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(matr2)
print(type(matr2))

print(np.bmat('matr1 matr2; matr1, matr2'))   # 矩阵拼接

print(matr1.T)   # 矩阵的转置
print(matr1.I)   # 矩阵的逆

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [89]:
# 通用函数
arr1 = np.array([0.2, 0.4, 0.6])
arr2 = np.array([0.2, 0.6, 0.78])
list1 = [0.2, 0.4, 0.6]

print(arr1 + 1)
# print(list1 + 1)  # 非法操作
print(arr1 * 2)
print(list1 * 2)    # 注意其返回结果

print(arr1 + arr2)  # 对应元素相加
print(arr1 * arr2)  # 对应元素相乘

print(arr1 > 0)
print(arr1 < arr2)

print(np.any(arr1 == 0.2))   # 逻辑 or
print(np.all(arr1 == 0.2))   # 逻辑 and

[1.2 1.4 1.6]
[0.4 0.8 1.2]
[0.2, 0.4, 0.6, 0.2, 0.4, 0.6]
[0.4  1.   1.38]
[0.04  0.24  0.468]
[ True  True  True]
[False  True  True]
True
False


In [90]:
# 广播机制
arr3 = np.arange(1, 13).reshape([4, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([[1], [2], [3], [4]])
print(arr3)
print(arr4)
print(arr5)

print(arr3 + arr4)
print(arr3 + arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]
[[1]
 [2]
 [3]
 [4]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


## 利用 NumPy 进行统计分析

In [91]:
import numpy as np

In [95]:
# 读写二进制文件
arr1 = np.arange(1, 13).reshape([4, 3])
arr2 = np.arange(1, 13).reshape([3, 4])
print(arr1)
print(arr2)

np.save('C:/Users/VICTUS/OneDrive - stu.fynu.edu.cn/python数据分析与应用ZM/tmp/arr1.npy', arr1)        # 保存数据
arr1_load = np.load('C:/Users/VICTUS/OneDrive - stu.fynu.edu.cn/python数据分析与应用ZM/tmp/arr1.npy')  # 读取数据
print(arr1_load)

np.savez('C:/Users/VICTUS/OneDrive - stu.fynu.edu.cn/python数据分析与应用ZM/tmp/arr1&2.npz', arr1, arr2)   # 保存多个数组数据
arr1_2_load = np.load('C:/Users/VICTUS/OneDrive - stu.fynu.edu.cn/python数据分析与应用ZM/tmp/arr1&2.npz')

print(arr1_2_load)
print(arr1_2_load.files)     # 查看数据文件中有哪些数组对象
print(arr1_2_load['arr_0'])  # 访问数据文件中的具体数组对象

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
['arr_0', 'arr_1']
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [96]:
# 读写txt文件
np.savetxt('C:/Users/VICTUS/OneDrive - stu.fynu.edu.cn/python数据分析与应用ZM/tmp/arr1.txt', arr1, delimiter=',')   # 保存数据
np.loadtxt('C:/Users/VICTUS/OneDrive - stu.fynu.edu.cn/python数据分析与应用ZM/tmp/arr1.txt', delimiter=',')         # 读取数据

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [97]:
# 使用数组进行简单统计分析
arr3 = np.random.randint(1, 10, (3, 4))
print(arr3)

arr3.sort(axis=0)   # 对数组元素按大小进行排序
print(arr3)
print(arr3.argsort(axis=0))   # 返回排序后的下标

print(np.tile(arr3, 2))      # 对数组进行复制操作
print(np.repeat(arr3, 2, axis=1))  # 对数组元素进行复制

print(arr3.mean())    # 统计数组所有元素的均值
print(arr3.mean(axis=0))   # 按列统计数组的均值
print(arr3.max(axis=0))

print(arr3.argmax(axis=0))   # 找出每列元素最大值的位置

[[9 6 8 4]
 [3 7 1 4]
 [5 6 3 5]]
[[3 6 1 4]
 [5 6 3 4]
 [9 7 8 5]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[3 6 1 4 3 6 1 4]
 [5 6 3 4 5 6 3 4]
 [9 7 8 5 9 7 8 5]]
[[3 3 6 6 1 1 4 4]
 [5 5 6 6 3 3 4 4]
 [9 9 7 7 8 8 5 5]]
5.083333333333333
[5.66666667 6.33333333 4.         4.33333333]
[9 7 8 5]
[2 2 2 2]
